### ISSUE TITLE
Add Susi as a Gitter Chat Bot

### ISSUE THREAD

**Issue by shivenmian** [fossasia/susi_slackbot#14]
@mariobehling @sudheesh001 As a continuation of Issue #1, I'd like to implement Susi for Gitter as a bot. Since our entire team is Gitter based, everyone can conveniently test and use this too. I will get onto this in the coming week.

**Comment by sudheesh001** [comment]
:+1:

**Comment by Abhi2424shek** [comment]
@shivenmian still on it?

**Comment by AliAyub007** [comment]
Its already complete here https://github.com/fossasia/susi_gitterbot so closing it.
