### ISSUE TITLE
Line: Susi Chat Bot

### ISSUE THREAD

**Issue by PrabhanshuAttri** [fossasia/susi_slackbot#24]
@mariobehling @sudheesh001 @jig08 
This is regarding #1 . I have deployed a Susi chat bot on line.

Use this QR Code to test it.
![screen shot 2016-11-23 at 4 52 24 am](https://cloud.githubusercontent.com/assets/4739486/20546107/196d7ba8-b139-11e6-9223-653debe9958d.png)

Sample image
![photo278017601508059449](https://cloud.githubusercontent.com/assets/4739486/20546068/e79b44c0-b138-11e6-8bb4-2ba6102bbe79.jpg)

Let me know if it's good enough.

**Comment by shivenmian** [comment]
@PrabhanshuAttri Line as in Line messenger?

Sounds good. Please drop in a line at https://gitter.im/loklak/loklak with the link of your repository (which contains this code). If the code and docs are fine, we'll fork your repo to the main FOSSASIA organisation. :)

**Comment by Abhi2424shek** [comment]
Can't we close this? @shivenmian
