### ISSUE TITLE
live Version of Susi Messenger is not working.

### ISSUE THREAD

**Issue by dexta11** [fossasia/susi_slackbot#25]
As continuation with the title , edit documentation by telling how we can make use of live messenger with susi_ffbot. 
 #![asksusi](https://cloud.githubusercontent.com/assets/22263960/22769897/05a3d7aa-eeb2-11e6-9b9f-4986943a8974.png)

**Comment by enigmaeth** [comment]
@mariobehling @shivenmian @sudheesh001  
I think that this is an issue with the  Facebook Page access token. If there is an issue with authentication,  we could ask the maintainer/admin of AskSusi page on FB to update the access token and keys.

**Comment by shivenmian** [comment]
You guys are commenting on the wrong repo. The FB messenger repo is https://github.com/fossasia/susi_fbbot/, please see that.

The issue is the API endpoint, I think it changed. Will fix it.
