### ISSUE TITLE
Viber: susi chat bot 

### ISSUE THREAD

**Issue by Manveer695** [fossasia/susi_slackbot#26]
Greetings, 

Hi, I am Manveer Singh. I am into computer science and engineering. I want to be a part of GSOC, 2017 under Fossasia. 
I wanted to plug in the susi bot to viber messenger. So am i supposed to make a git repo of my code and send it to your team? 

Thanks.

**Comment by Abhi2424shek** [comment]
Pls make it, if it works we will import it, but discuss such things in chatrooms and not open up issues! :)
@shivenmian pls close this up.

**Comment by shivenmian** [comment]
Yeah so work on it yourself. If it works, we'll import it. Thanks! :)
